### ISSUE TITLE
Oomph-Installer:P2-Director Task fails 

### ISSUE THREAD

**Issue by asc666** [Flugtiger/birt#47]
due to https://support.sonatype.com/hc/en-us/articles/360041287334 the task fails with 

ERROR: org.eclipse.equinox.p2.transport.ecf code=1002 HTTP Server 'Not Implemented': http://repo1.maven.org/maven2/.m2e/connectors/m2eclipse-tycho/0.8.1/N/LATEST/content.xml
ERROR: org.eclipse.ecf.identity code=0 HttpComponents connection error response code 501.
  at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:293)
  at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Please adjust the Url to 
**https**://repo1.maven.org/maven2/.m2e/connectors/m2eclipse-tycho/0.8.1/N/LATEST/content.xml

**Comment by asc666** [comment]
fixed
